server:
  hostname: 0.0.0.0
  port: 2002
  trustProxy:
    - loopback
  clusters: 0
services:
  database:
    type: mariadb
    host: db
    port: 3306
    username: lyrio
    password: lyrio-password
    database: lyrio
  minio:
    default:
      endpoint: http://minio:9000
      signEndpoint: null
    forUserUpload: 
      endpoint: http://127.0.0.1:9090
      signEndpoint: null
    forUserDownload: 
      endpoint: http://127.0.0.1:9090
      signEndpoint: null
    forJudge:
      endpoint: http://127.0.0.1:9090
      signEndpoint: null
    accessKey: AKAK
    secretKey: SKSKSKSK
    bucket: lyrio-files
  redis: redis://redis:6379
  mail:
    address: no-reply@lyrio.test
    transport: smtp://username:password@lyrio-smtp.test:25
security:
  crossOrigin:
    enabled: true
    whiteList:
      - http://127.0.0.1:8080
      - http://localhost:8080
  sessionSecret: don't leak this
  maintainceKey: also don't leak this
  recaptcha:
    secretKey: null
    useRecaptchaNet: false
    proxyUrl: null
  rateLimit:
    maxRequests: 200
    durationSeconds: 10
preference:
  siteName: Lyrio
  security:
    recaptchaEnabled: false
    recaptchaKey: null
    requireEmailVerification: true
    allowUserChangeUsername: true
    allowEveryoneCreateProblem: true
    allowNonPrivilegedUserEditPublicProblem: true
    allowOwnerManageProblemPermission: false
    allowOwnerDeleteProblem: true
    allowEveryoneCreateDiscussion: true
    discussionDefaultPublic: true
    discussionReplyDefaultPublic: true
  pagination:
    homepageUserList: 10
    homepageProblemList: 10
    problemSet: 50
    searchProblemsPreview: 7
    submissions: 10
    submissionStatistics: 10
    userList: 30
    userAuditLogs: 10
    discussions: 10
    searchDiscussionsPreview: 7
    discussionReplies: 40
    discussionRepliesHead: 20
    discussionRepliesMore: 20
  misc:
    appLogo: default
    appLogoForTheme:
      pure: original
      far: inverted
    googleAnalyticsId: null
    plausibleApiEndpoint: null
    gravatarCdn: https://gravatar.com
    redirectLegacyUrls: false
    legacyContestsEntryUrl: null
    homepageUserListOnMainView: true
    sortUserByRating: false
    renderMarkdownInUserBio: false
    discussionReactionEmojis: [👍, 👎, 😄, 😕, ❤️, 🤔, 🤣, 🌿, 🍋, 🕊️]
    discussionReactionAllowCustomEmojis: true
  serverSideOnly:
    discussionReactionCustomEmojisBlacklist: /(\uD83C[\uDDE6-\uDDFF]){2}/
    dynamicTaskPriority: true
resourceLimit:
  problemTestdataFiles: 40
  problemTestdataSize: 134217728
  problemAdditionalFileFiles: 40
  problemAdditionalFileSize: 134217728
  problemSamplesToRun: 10
  problemTestcases: 20
  problemTimeLimit: 2000
  problemMemoryLimit: 512
  submissionFileSize: 10485760
queryLimit:
  problemSet: 100
  submissions: 10
  submissionStatistics: 10
  searchUser: 10
  searchGroup: 10
  userList: 100
  userAuditLogs: 20
  discussions: 20
  discussionReplies: 50
judge:
  limit:
    compilerMessage: 524288
    outputSize: 104857600
    dataDisplay: 128
    dataDisplayForSubmitAnswer: 128
    stderrDisplay: 5120
eventReport:
  telegramBotToken: null
  telegramApiRoot: null
  sentTo: "@example"
  proxyUrl: null
vendor:
  ip2region: null
